import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { BLOG_CONTENT } from '@/lib/blog-content';

function adminDb() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  );
}

const staticPosts = [
  { title: 'Best Dog Food Brands in India for 2026', slug: 'best-dog-food-brands-india', excerpt: "India's top dog food brands, nutrition ratings, and matching recipes for every breed and budget.", featured_image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=1600&q=85&auto=format&fit=crop', category: 'Nutrition', author: 'PetopiaCare Experts', read_time_minutes: 8, status: 'published', seo_title: 'Best Dog Food Brands in India | 2026 Pet Nutrition Guide', seo_description: 'Discover top dog food brands in India for 2026, with nutrition tips, price comparisons, and feeding advice for every breed.', seo_keywords: 'dog food india, best dog food, dog nutrition, pet food brands' },
  { title: 'Homemade Dog Food Recipe for Indian Dogs', slug: 'homemade-dog-food-recipe-indian-dogs', excerpt: 'Nutritious, budget-friendly dog food recipes using Indian kitchen ingredients.', featured_image: 'https://images.unsplash.com/photo-1568572933382-74d440642117?w=1600&q=85&auto=format&fit=crop', category: 'Nutrition', author: 'PetopiaCare Experts', read_time_minutes: 10, status: 'published', seo_title: 'Homemade Dog Food Recipe for Indian Dogs', seo_description: 'Step-by-step homemade dog food recipes for Indian dogs. Budget-friendly, healthy ingredients.', seo_keywords: 'homemade dog food recipe, dog food recipes india, budget dog food' },
  { title: 'Stop Dog Pulling on Leash: Training Tips That Work', slug: 'stop-dog-pulling-on-leash', excerpt: 'Turn daily walks into a calm experience with proven positive-reinforcement leash training techniques.', featured_image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=1600&q=85&auto=format&fit=crop', category: 'Training', author: 'PetopiaCare Experts', read_time_minutes: 7, status: 'published', seo_title: 'How to Stop Dog Pulling on Leash | Training Guide', seo_description: 'Learn leash training tips to stop your dog from pulling.', seo_keywords: 'dog pulling leash, leash training, dog walking tips' },
  { title: 'Summer Dog Care in India: Hydration & Heat Safety', slug: 'summer-dog-care-india', excerpt: "Keep your dog safe during India's hot months. Heatstroke prevention, hydration tips, and summer grooming.", featured_image: 'https://images.unsplash.com/photo-1537151608804-ea6f25dc1005?w=1600&q=85&auto=format&fit=crop', category: 'Health', author: 'PetopiaCare Experts', read_time_minutes: 8, status: 'published', seo_title: 'Summer Dog Care India | Hydration & Heat Safety Tips', seo_description: 'Protect your dog from Indian summer heat.', seo_keywords: 'summer dog care, heat safety for dogs' },
  { title: 'How to Choose the Right Dog Harness', slug: 'choosing-safe-dog-harness', excerpt: 'A complete buying guide — comparing no-pull, padded, and polymer harnesses for Indian breeds.', featured_image: 'https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=1600&q=85&auto=format&fit=crop', category: 'Products', author: 'PetopiaCare Experts', read_time_minutes: 6, status: 'published', seo_title: 'Safe Dog Harness Guide | Best Harnesses for Dogs', seo_description: 'Choose the safest dog harness for your pet.', seo_keywords: 'dog harness india, safe harness' },
  { title: 'Dog Grooming Guide for Indian Breeds', slug: 'grooming-tips-indian-dogs', excerpt: 'Coat care, nail trimming, ear cleaning and skin health routines tailored for Indian weather and breeds.', featured_image: 'https://images.unsplash.com/photo-1625213327543-b24c2fc0d6ee?w=1600&q=85&auto=format&fit=crop', category: 'Grooming', author: 'PetopiaCare Experts', read_time_minutes: 7, status: 'published', seo_title: 'Indian Dog Grooming Tips | Coat, Nails & Skin Care', seo_description: 'Master dog grooming in India.', seo_keywords: 'dog grooming india, pet grooming tips' },
  { title: 'Puppy Training Basics Every New Owner Needs', slug: 'puppy-training-basics', excerpt: 'Start your puppy right — house training, socialisation, bite inhibition, and reward-based first commands.', featured_image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=1600&q=85&auto=format&fit=crop', category: 'Training', author: 'PetopiaCare Experts', read_time_minutes: 9, status: 'published', seo_title: 'Puppy Training Basics | New Dog Owner Guide', seo_description: 'Learn puppy training basics for Indian homes.', seo_keywords: 'puppy training, new dog owner' },
  { title: 'Common Dog Health Issues in India & When to See a Vet', slug: 'common-dog-health-issues', excerpt: "Tick fever, mange, parvovirus and more — symptoms to watch for and when it's a vet emergency.", featured_image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=1600&q=85&auto=format&fit=crop', category: 'Health', author: 'Dr. Priya Sharma', read_time_minutes: 10, status: 'published', seo_title: 'Common Dog Health Issues | Vet Advice for Indian Pets', seo_description: 'Identify common dog health issues early.', seo_keywords: 'dog health issues, vet advice' },
  { title: 'Indian Pariah Dog: The Complete Breed Guide', slug: 'indian-pariah-dog-guide', excerpt: 'Everything about the Desi dog — temperament, care, training, and why adopting an INDog is the best decision.', featured_image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=1600&q=85&auto=format&fit=crop', category: 'Breeds', author: 'PetopiaCare Experts', read_time_minutes: 9, status: 'published', seo_title: 'Indian Pariah Dog Breed Guide | INDog Complete Care', seo_description: 'Complete guide to the Indian Pariah Dog.', seo_keywords: 'indian pariah dog, INDog, desi dog' },
  { title: 'Vaccination Schedule for Dogs in India — 2026 Guide', slug: 'dog-vaccination-schedule-india', excerpt: 'Core vaccines, timing, cost, and what to expect — the complete guide for Indian dog owners.', featured_image: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=1600&q=85&auto=format&fit=crop', category: 'Health', author: 'Dr. Priya Sharma', read_time_minutes: 8, status: 'published', seo_title: 'Dog Vaccination Schedule India 2026', seo_description: 'Complete dog vaccination schedule for India.', seo_keywords: 'dog vaccination india, vaccine schedule' },
  { title: 'Tick Prevention for Dogs in India: Year-Round Guide', slug: 'tick-prevention-dogs-india', excerpt: 'Spot-on treatments, tick collars, and environmental control — comprehensive tick prevention for Indian conditions.', featured_image: 'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?w=1600&q=85&auto=format&fit=crop', category: 'Health', author: 'PetopiaCare Experts', read_time_minutes: 7, status: 'published', seo_title: 'Tick Prevention for Dogs India | Year-Round Guide', seo_description: 'Protect your dog from ticks year-round in India.', seo_keywords: 'tick prevention dogs india' },
  { title: "Labrador Retriever in India: Owner's Complete Care Guide", slug: 'labrador-care-guide-india', excerpt: "Labs are India's most popular breed. Here's everything you need to raise one well in the Indian climate.", featured_image: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=1600&q=85&auto=format&fit=crop', category: 'Breeds', author: 'PetopiaCare Experts', read_time_minutes: 11, status: 'published', seo_title: 'Labrador Retriever Care Guide India', seo_description: 'Complete care guide for Labrador Retrievers in India.', seo_keywords: 'labrador care india' },
  { title: 'Dog Dental Care Guide: Healthy Teeth for Happy Dogs', slug: 'dog-dental-care-guide', excerpt: 'Healthy teeth keep your dog smiling. Learn daily brushing, teething, and dental treat routines.', featured_image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=1600&q=85&auto=format&fit=crop', category: 'Health', author: 'PetopiaCare Experts', read_time_minutes: 5, status: 'published', seo_title: 'Dog Dental Care Guide', seo_description: "Keep your dog's teeth clean.", seo_keywords: 'dog dental care, dog teeth cleaning' },
  { title: 'Traveling with Your Dog in India: Planning, Safety, and Comfort', slug: 'traveling-with-dog-india', excerpt: 'Make dog travel easy with packing lists, transport tips, and destination advice for Indian pet families.', featured_image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&q=85&auto=format&fit=crop', category: 'Lifestyle', author: 'PetopiaCare Experts', read_time_minutes: 6, status: 'published', seo_title: 'Traveling with Dogs in India | Pet Travel Tips', seo_description: 'Prepare for safe and comfortable dog travel in India.', seo_keywords: 'traveling with dog, pet travel india' },
  { title: 'Introducing a New Puppy to Your Home', slug: 'introducing-new-puppy', excerpt: 'Bring home your puppy with confidence using preparation tips for sleeping, feeding, and family introduction.', featured_image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=1600&q=85&auto=format&fit=crop', category: 'Lifestyle', author: 'PetopiaCare Experts', read_time_minutes: 5, status: 'published', seo_title: 'Introducing a New Puppy | Home Preparation Guide', seo_description: 'Learn how to welcome a new puppy.', seo_keywords: 'new puppy guide, puppy introduction' },
  { title: 'Rainy Season Dog Care: Waterproof Gear & Clean Paws', slug: 'rainy-season-dog-care', excerpt: 'Keep your dog dry, clean, and comfortable during monsoon with easy grooming and rain-ready gear.', featured_image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=1600&q=85&auto=format&fit=crop', category: 'Health', author: 'PetopiaCare Experts', read_time_minutes: 5, status: 'published', seo_title: 'Rainy Season Dog Care | Monsoon Pet Tips India', seo_description: 'Manage monsoon pet care.', seo_keywords: 'rainy season dog care, monsoon pet care' },
  { title: 'Senior Dog Care Tips: Comfort, Diet, and Gentle Exercise', slug: 'senior-dog-care-tips', excerpt: 'Support your aging dog with softer diets, joint-friendly exercise, and comfort-focused home changes.', featured_image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=1600&q=85&auto=format&fit=crop', category: 'Health', author: 'PetopiaCare Experts', read_time_minutes: 6, status: 'published', seo_title: 'Senior Dog Care Tips | Comfort & Nutrition India', seo_description: 'Care for aging dogs in India.', seo_keywords: 'senior dog care, older dog tips' },
  { title: 'A Practical Dog Breed Guide for Indian Families', slug: 'dog-breed-guide-indian-families', excerpt: 'Choose the right dog breed for your lifestyle with this Indian-friendly breed guide and care comparison.', featured_image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=1600&q=85&auto=format&fit=crop', category: 'Breeds', author: 'PetopiaCare Experts', read_time_minutes: 7, status: 'published', seo_title: 'Dog Breed Guide India | Best Breeds for Indian Families', seo_description: 'Explore the best dog breeds for Indian homes.', seo_keywords: 'dog breed guide india' },
  { title: 'Natural Dog Treats You Can Make at Home', slug: 'natural-dog-treats-at-home', excerpt: 'Create healthy dog treats with simple ingredients and avoid processed snacks with this easy homemade recipe guide.', featured_image: 'https://images.unsplash.com/photo-1568572933382-74d440642117?w=1600&q=85&auto=format&fit=crop', category: 'Nutrition', author: 'PetopiaCare Experts', read_time_minutes: 5, status: 'published', seo_title: 'Natural Dog Treats at Home | Healthy Pet Recipes India', seo_description: 'Make healthy, homemade dog treats.', seo_keywords: 'homemade dog treats, natural dog snacks' },
  { title: 'Building a Dog-Friendly Home in India', slug: 'building-dog-friendly-home-india', excerpt: 'Make your home safe and comfortable for dogs with smart layout, storage, and care zones.', featured_image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&q=85&auto=format&fit=crop', category: 'Lifestyle', author: 'PetopiaCare Experts', read_time_minutes: 5, status: 'published', seo_title: 'Build a Dog-Friendly Home India', seo_description: 'Create a dog-friendly home with safe zones.', seo_keywords: 'dog friendly home india' },
  { title: 'How to Manage Dog Anxiety with Routine and Comfort', slug: 'manage-dog-anxiety', excerpt: 'Help anxious dogs feel calm with routine, mental stimulation, and gentle behavior support.', featured_image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=1600&q=85&auto=format&fit=crop', category: 'Training', author: 'PetopiaCare Experts', read_time_minutes: 6, status: 'published', seo_title: 'Manage Dog Anxiety | Calm Pet Behavior Tips India', seo_description: 'Reduce dog anxiety with routine.', seo_keywords: 'dog anxiety india, separation anxiety dog' },
  { title: 'Benefits of Regular Dog Exercise for Indian Pets', slug: 'benefits-regular-dog-exercise', excerpt: "Discover how daily movement improves your dog's health, mood, and behavior in Indian climates.", featured_image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=1600&q=85&auto=format&fit=crop', category: 'Health', author: 'PetopiaCare Experts', read_time_minutes: 6, status: 'published', seo_title: 'Regular Dog Exercise Benefits | Healthy Dog Lifestyle India', seo_description: 'Learn the benefits of regular dog exercise.', seo_keywords: 'dog exercise india, pet fitness' },
  { title: 'Dog Safety Tips for Urban Living in India', slug: 'dog-safety-urban-indirapuram', excerpt: 'Protect your dog in city life with leash safety, traffic awareness, and secure balcony habits.', featured_image: 'https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=1600&q=85&auto=format&fit=crop', category: 'Health', author: 'PetopiaCare Experts', read_time_minutes: 5, status: 'published', seo_title: 'Dog Safety Urban India | City Pet Care Tips', seo_description: 'Urban dog safety guide for Indian cities.', seo_keywords: 'dog safety india, urban pet tips' },
  { title: 'Choosing the Right Dog Bed for Comfort and Support', slug: 'choosing-right-dog-bed', excerpt: 'Find the most comfortable dog bed for your pet, whether they prefer orthopaedic support or cozy nesting style.', featured_image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=1600&q=85&auto=format&fit=crop', category: 'Products', author: 'PetopiaCare Experts', read_time_minutes: 5, status: 'published', seo_title: 'Best Dog Bed Guide India | Comfort & Support for Dogs', seo_description: 'Choose the right dog bed for Indian conditions.', seo_keywords: 'dog bed india' },
  { title: 'Allergy Care for Dogs in India: Seasonal Grooming Tips', slug: 'allergy-care-dogs-india', excerpt: 'Manage dog allergies with seasonal grooming, diet changes, and home-cleaning routines.', featured_image: 'https://images.unsplash.com/photo-1625213327543-b24c2fc0d6ee?w=1600&q=85&auto=format&fit=crop', category: 'Health', author: 'PetopiaCare Experts', read_time_minutes: 6, status: 'published', seo_title: 'Dog Allergy Care India | Seasonal Grooming & Diet Tips', seo_description: 'Manage dog allergies in India.', seo_keywords: 'dog allergies india, seasonal pet care' },
];

export async function POST() {
  try {
    const db = adminDb();

    const postsToInsert = staticPosts.map(post => ({
      ...post,
      content: BLOG_CONTENT[post.slug] ?? `<h2>${post.title}</h2><p>${post.excerpt}</p>`,
    }));

    const { error, count } = await db
      .from('blog_posts')
      .upsert(postsToInsert, { onConflict: 'slug', count: 'exact' });

    if (error) {
      console.error('Seed blogs error:', error);
      return NextResponse.json({ ok: false, error: error.message }, { status: 500 });
    }

    return NextResponse.json({ ok: true, count: count ?? postsToInsert.length });
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Unknown error';
    return NextResponse.json({ ok: false, error: msg }, { status: 500 });
  }
}
