-- ============================================================
-- PetopiaCare Phase 3 Seed Data
-- 10 entries per table — Indian breed & climate context
-- Run AFTER all 5 migration files
-- ============================================================


-- ────────────────────────────────────────────────────────────
-- TABLE 1: dog_breeds (10 entries)
-- ────────────────────────────────────────────────────────────

INSERT INTO dog_breeds (slug, name, size, weight_range, height_range, temperament, exercise_level, grooming_needs, shedding, common_health_issues, life_expectancy, origin, behavioral_traits, training_difficulty, good_with_kids, good_with_pets, full_description, care_tips, nutrition_notes, is_published) VALUES

('labrador-retriever', 'Labrador Retriever', 'large', '25–36 kg', '55–62 cm',
 ARRAY['friendly', 'outgoing', 'playful', 'gentle', 'trusting'],
 'high', 'moderate', 'high',
 ARRAY['hip dysplasia', 'obesity', 'elbow dysplasia', 'eye conditions'],
 '10–12 years', 'Canada',
 'Highly food-motivated and eager to please. Adapts well to apartment life if exercised daily. Prone to chewing when bored.',
 'easy', true, true,
 'The Labrador Retriever is India''s most popular dog breed. Friendly, gentle, and highly trainable, Labs thrive in family environments. Their double coat sheds heavily twice a year — daily brushing during shedding season keeps the home clean. They are water-loving dogs and enjoy swimming.',
 'Brush coat 2–3 times per week. Bathe monthly. Clean ears weekly as they are prone to infections. Provide at least 60–90 minutes of exercise daily to prevent obesity.',
 'Labs are prone to weight gain. Feed measured portions 2x daily. High-protein kibble is recommended. Avoid free-feeding. Adult Labs (25–36 kg) typically need 2.5–3.5 cups of dry food per day split across two meals.',
 true),

('german-shepherd', 'German Shepherd', 'large', '22–40 kg', '55–65 cm',
 ARRAY['loyal', 'courageous', 'confident', 'intelligent', 'protective'],
 'very_high', 'moderate', 'high',
 ARRAY['hip dysplasia', 'degenerative myelopathy', 'bloat', 'skin allergies'],
 '9–13 years', 'Germany',
 'Alert and highly trainable. Can be aloof with strangers but deeply bonds with family. Needs a clear pack leader or may become anxious.',
 'easy', true, true,
 'German Shepherds are among the most versatile working dogs in the world. In India, they are popular as guard dogs, police dogs, and family companions. Intelligent and hardworking, they need both mental stimulation and physical exercise to be content.',
 'Double coat requires brushing 3–4 times weekly. Provide 2 hours of activity daily — walks, fetch, agility. Mental enrichment (puzzle toys, training) prevents destructive boredom. Socialise from puppyhood.',
 'Feed a high-protein, large-breed formula. Adult intake: 3–4 cups dry food per day. Avoid exercise immediately after meals to reduce bloat risk. Omega-3 supplements support joint and coat health.',
 true),

('indian-pariah-dog', 'Indian Pariah Dog', 'medium', '14–22 kg', '46–56 cm',
 ARRAY['alert', 'intelligent', 'independent', 'loyal', 'adaptable'],
 'moderate', 'minimal', 'moderate',
 ARRAY['mange', 'tick fever', 'worm infestations'],
 '13–15 years', 'India',
 'Highly independent thinker. Bonds deeply with family but wary of strangers. Rarely barks without reason — an excellent natural watchdog.',
 'moderate', true, true,
 'The Indian Pariah Dog (also known as the Desi Dog or INDog) is one of the oldest dog breeds in existence, dating back over 4,500 years. Naturally evolved for the Indian subcontinent, they are extremely hardy, disease-resistant, and low-maintenance. Adopting a Desi dog is the most sustainable choice for Indian families.',
 'Short coat requires almost no grooming — a weekly brush is sufficient. Naturally active; daily walks of 30–45 minutes keep them healthy. Exceptional immunity but stay current on deworming, tick prevention, and core vaccines.',
 'Low dietary requirements compared to imported breeds. Quality kibble or home-cooked rice + chicken/paneer meals work well. Avoid overly rich food. Feed 1.5–2 cups dry food twice daily for a 15 kg dog.',
 true),

('golden-retriever', 'Golden Retriever', 'large', '25–34 kg', '51–61 cm',
 ARRAY['gentle', 'trustworthy', 'kind', 'confident', 'patient'],
 'high', 'high', 'high',
 ARRAY['hip dysplasia', 'cancer', 'heart disease', 'obesity'],
 '10–12 years', 'Scotland',
 'Exceptionally gentle and patient — rarely aggressive. Loves to carry objects and retrieve. Can suffer separation anxiety if left alone too long.',
 'easy', true, true,
 'Golden Retrievers are beloved family dogs known for their warm, gentle temperament. In India''s hot climate, their dense double coat makes them prone to overheating — air conditioning or fans during summer are essential. They need significant grooming but reward owners with unwavering loyalty.',
 'Brush the thick coat 4–5 times per week; daily during shedding season. Trim paws and ears regularly. Keep them cool in summer — exercise in early morning or evening only. At least 60–90 min of daily activity.',
 'High-quality large-breed kibble with joint-supporting ingredients (glucosamine, chondroitin). Feed measured 2x daily — Goldens are as food-motivated as Labs and equally prone to obesity. 2.5–3.5 cups per day for adults.',
 true),

('beagle', 'Beagle', 'small', '9–11 kg', '33–41 cm',
 ARRAY['curious', 'friendly', 'merry', 'determined', 'gentle'],
 'high', 'minimal', 'moderate',
 ARRAY['hypothyroidism', 'epilepsy', 'obesity', 'intervertebral disc disease'],
 '12–15 years', 'England',
 'Scent-driven and easily distracted by smells. Can be stubborn and selective about commands. Rarely aggressive; excellent with children.',
 'moderate', true, true,
 'Beagles are sturdy, compact dogs that adapt well to Indian apartment living — provided they get enough exercise. Their powerful nose means they follow scents relentlessly, so a secure garden or leash walks are essential. Their baying howl can be loud, which neighbours may not appreciate.',
 'Short coat is easy to maintain — weekly brush suffices. Clean long ears weekly to prevent infections. Exercise 45–60 min daily. Use puzzle feeders to satisfy their active mind. Train with high-value treats for best results.',
 'Prone to obesity — strict portion control is critical. 1–1.5 cups dry kibble daily split into two meals. Avoid table scraps entirely. High-fibre food options help them feel full longer.',
 true),

('pomeranian', 'Pomeranian', 'small', '1.8–3.5 kg', '18–22 cm',
 ARRAY['bold', 'lively', 'playful', 'curious', 'alert'],
 'moderate', 'very_high', 'high',
 ARRAY['tracheal collapse', 'dental disease', 'luxating patella', 'alopecia x'],
 '12–16 years', 'Germany/Poland',
 'Big personality in a tiny body. Can be bossy and opinionated. Prone to "small dog syndrome" if not trained firmly from puppyhood. Excellent watchdog despite the size.',
 'moderate', true, false,
 'Pomeranians are feisty, intelligent, and deeply loyal to their owners. Their thick double coat requires significant maintenance, especially in India''s humid climate which can cause matting and skin issues. Despite their small size, they are bold and spirited — often unaware of how tiny they are.',
 'Brush the double coat daily to prevent matting. Professional grooming every 6–8 weeks. Keep cool in summer — very prone to heat stroke. Dental care is critical: daily teeth brushing or dental chews. Handle gently — fragile bones.',
 'Very small stomach — feed 3 small meals daily or use an auto-feeder. High-quality small-breed kibble. 0.25–0.5 cup per day total. Dental-health formulas are beneficial. Avoid large kibble pieces.',
 true),

('rottweiler', 'Rottweiler', 'large', '35–60 kg', '56–69 cm',
 ARRAY['loyal', 'loving', 'confident', 'calm', 'courageous'],
 'high', 'minimal', 'moderate',
 ARRAY['hip dysplasia', 'heart conditions', 'bloat', 'cancer'],
 '8–10 years', 'Germany',
 'Deeply devoted to family but naturally wary of strangers. Can be dominant — needs a confident, consistent owner. Without proper socialisation, can develop aggression issues.',
 'moderate', true, false,
 'Rottweilers are powerful, intelligent working dogs with a calm, self-assured temperament when well-trained. Popular guard dogs in India. Their short coat makes them more suitable for Indian weather than many other large breeds. Early socialisation and obedience training are non-negotiable.',
 'Short coat needs only weekly brushing. Exercise 1–1.5 hours daily — mental and physical. Obedience training from 8 weeks. Socialise extensively with people and other animals early. Monitor food intake as they can gain weight post-spaying/neutering.',
 'Large-breed formula with controlled calcium levels for proper bone development. Adults need 4–5 cups dry food daily split across two meals. Elevate food bowls to reduce bloat risk. Avoid vigorous exercise 1 hour before and after meals.',
 true),

('shih-tzu', 'Shih Tzu', 'small', '4–7.5 kg', '20–28 cm',
 ARRAY['affectionate', 'playful', 'outgoing', 'loyal', 'alert'],
 'low', 'very_high', 'low',
 ARRAY['brachycephalic syndrome', 'hip dysplasia', 'eye conditions', 'dental disease'],
 '10–18 years', 'Tibet/China',
 'Loves attention and human companionship — can develop separation anxiety. Generally friendly with everyone. Not great in extreme heat due to flat face.',
 'easy', true, true,
 'Shih Tzus are companion dogs bred for royalty and they carry that expectation into modern homes. Their beautiful flowing coat is their most distinctive feature but requires daily grooming. In India''s hot climate, many owners keep them in a "puppy cut" year-round. They are indoor dogs that cannot handle heat well.',
 'Daily brushing and combing essential. Trim around eyes and ears regularly. Keep indoors with AC in summer — brachycephalic breeds are high-risk in heat. Short walks in early morning/evening only. Clean facial folds daily.',
 'Small-breed formula with real meat as first ingredient. 0.5–1 cup dry food split across two meals. High omega-3 content supports coat health. Fresh water always available — brachycephalic dogs dehydrate faster.',
 true),

('doberman-pinscher', 'Doberman Pinscher', 'large', '27–45 kg', '61–72 cm',
 ARRAY['fearless', 'loyal', 'intelligent', 'alert', 'energetic'],
 'very_high', 'minimal', 'low',
 ARRAY['dilated cardiomyopathy', 'wobbler syndrome', 'hip dysplasia', 'von Willebrand disease'],
 '10–13 years', 'Germany',
 'Highly alert and sensitive to owner''s emotions. Can be anxious in unstable environments. Exceptionally fast learners — boredom leads to destructive behaviour.',
 'easy', true, false,
 'Dobermans are sleek, powerful, and intensely loyal protection dogs. Their short coat makes them excellent for Indian weather — they handle heat much better than fluffy breeds. Dobermans need an experienced owner who can provide consistent leadership, extensive socialisation, and vigorous daily exercise.',
 'Minimal grooming — weekly wipe-down with a damp cloth. Exercise 1.5–2 hours daily minimum. Mental stimulation through advanced training is essential. Cardiac screening recommended annually after age 2. Keep warm in winter — thin coat offers little insulation.',
 'High-protein diet to support lean muscle mass. Large-breed formula. 3.5–4.5 cups per day for adults split across two meals. Avoid exercise 1 hour before/after meals — very prone to bloat. Supplement with cardiac-supportive nutrients (taurine, L-carnitine).',
 true),

('boxer', 'Boxer', 'large', '25–32 kg', '53–63 cm',
 ARRAY['fun-loving', 'bright', 'active', 'loyal', 'patient'],
 'very_high', 'minimal', 'low',
 ARRAY['brachycephalic syndrome', 'cardiomyopathy', 'hip dysplasia', 'cancer'],
 '10–12 years', 'Germany',
 'Perpetually playful and clownish — described as a dog that never grows up. High energy and needs firm boundaries. Excellent with children but can accidentally knock over small kids.',
 'moderate', true, true,
 'Boxers are enthusiastic, affectionate dogs that form deep bonds with their families. Their short muzzle makes them prone to breathing difficulties in India''s summer heat. Despite this, they are better suited to Indian conditions than long-coated breeds. They need significant exercise but minimal grooming — a fair trade.',
 'Weekly brushing and monthly bathing. Keep strictly indoors with cooling during summer heatwaves. Never exercise during peak afternoon hours. Exercise 1–1.5 hours daily in cool parts of the day. Drooling is normal.',
 'Quality large-breed kibble. Adults need 2.5–3.5 cups per day across two meals. Elevated food bowls can help reduce bloat risk. Avoid strenuous activity around mealtimes. Monitor weight — Boxers can become chunky without portion control.',
 true);


-- ────────────────────────────────────────────────────────────
-- TABLE 2: life_stages (10 entries)
-- ────────────────────────────────────────────────────────────

INSERT INTO life_stages (slug, name, age_range, behavioral_characteristics, nutrition_needs, exercise_requirements, health_concerns, training_tips, common_issues, special_care, is_published) VALUES

('neonatal', 'Neonatal', '0–2 weeks',
 'Eyes and ears closed. Completely dependent on mother. Sleeps 90% of the time. Responds only to warmth and touch.',
 'Exclusively mother''s milk. Colostrum in first 48 hours is critical for immunity. If mother is absent, use puppy milk replacer — never cow''s milk.',
 'No formal exercise. Natural rooting and crawling stimulates muscle development.',
 ARRAY['hypothermia', 'fading puppy syndrome', 'infection from mother', 'inadequate nutrition if separated'],
 'No training possible at this stage. Handle gently for a few minutes daily for early socialisation.',
 ARRAY['inability to nurse', 'rapid weight loss', 'constant crying', 'hypothermia'],
 'Maintain ambient temperature of 29–32°C for the whelping box. Weigh puppies daily — healthy puppies gain weight every day. Vet check within 24–48 hours of birth.',
 true),

('puppy-early', 'Early Puppy', '2–8 weeks',
 'Eyes open at 2 weeks. Begins play behaviour at 3–4 weeks. Critical socialisation window starts at 3 weeks. Begins learning bite inhibition from littermates.',
 'Transition from milk to soft puppy food at 3–4 weeks (weaning). By 6–8 weeks should eat puppy mush 4x daily. Ensure fresh water available.',
 'Short, gentle play sessions. 5 minutes of structured activity per month of age, twice daily.',
 ARRAY['parvovirus', 'distemper', 'roundworm', 'giardia', 'socialisation deficit'],
 'Puppies learn bite inhibition, play rules, and basic social cues from littermates — do not separate before 8 weeks. Begin name recognition and gentle handling exercises.',
 ARRAY['excessive crying', 'failure to nurse well', 'soft stool', 'low weight gain'],
 'First vet visit at 6 weeks for deworming and first vaccine assessment. Expose gently to sounds, surfaces, and handling. Do not expose to public spaces before vaccination.',
 true),

('puppy-socialisation', 'Socialisation Puppy', '8–16 weeks',
 'Peak socialisation window — every new positive experience now shapes behaviour for life. Begins testing boundaries. Short attention span. Fear period may occur around 8–10 weeks.',
 '4 meals per day for small breeds, 3 for medium/large. High-protein puppy formula. Calcium and phosphorus balance is critical for bone development. No adult food yet.',
 '5 minutes of structured play per month of age, 2x daily. Short leash walks in safe areas once vaccinated. Avoid stairs and jumps for large breeds.',
 ARRAY['parvovirus (if unvaccinated)', 'socialisation gaps', 'fear imprinting from bad experiences', 'parasites'],
 'Puppy classes are highly recommended. Focus on sit, stay, name, and recall. Short 5-minute sessions 3–4x daily are more effective than one long session. Always positive reinforcement — no punishment.',
 ARRAY['excessive biting', 'resource guarding', 'fearfulness', 'diarrhoea from food transitions'],
 'Complete vaccination series. Monthly deworming. Begin crate training and alone time gradually. Puppy-proof the home. Start tick and flea prevention.',
 true),

('puppy-juvenile', 'Juvenile Puppy', '4–6 months',
 'Increased independence. May "forget" previously learned commands — normal adolescent testing. Teething peaks — chewing behaviour intensifies. Rank in household becomes important.',
 '3 meals per day. Continue puppy formula. Nutritional needs are at their highest relative to body weight during this phase.',
 '15–20 minutes of controlled exercise 2x daily. Avoid high-impact activities for large breeds (jumping, stairs). Mental stimulation is as important as physical.',
 ARRAY['parvovirus if vaccine series incomplete', 'growth plate injuries from over-exercise', 'dental disease', 'intestinal parasites'],
 'Reinforce basic commands daily. Begin loose-leash walking. Introduce gentle exposure to new people, vehicles, and sounds. Enrol in puppy manners class if not already done.',
 ARRAY['destructive chewing', 'selective hearing', 'mouthing and nipping', 'play biting'],
 'All puppy vaccines should be complete by 16 weeks. Spay/neuter discussion with vet. Provide safe chew toys for teething. Supervise all play with children.',
 true),

('adolescent', 'Adolescent', '6–18 months',
 'Hormonal changes drive increased boldness, reactivity, and selective obedience. May regress on training. High energy. Sexually mature from 6–12 months depending on breed.',
 '2 meals per day. Transition to adult food begins: small/medium breeds at 12 months, large breeds at 18–24 months. Reduce caloric density as growth slows.',
 '30–45 minutes 2x daily of structured exercise. Off-leash time in secure areas. Mental enrichment daily.',
 ARRAY['orthopedic injuries from over-exercise', 'reproductive health issues if unsterilised', 'socialisation regression', 'anxiety'],
 'Consistency is critical — enforce all rules even when the dog "forgets". Continue obedience training. Advanced classes (agility, scent work) provide needed mental outlets. Patience is essential.',
 ARRAY['jumping on people', 'leash pulling', 'selective recall', 'food guarding'],
 'Spay or neuter at vet-recommended age. Annual booster vaccines begin. Monthly tick prevention essential in India. Check for heart health at annual vet visit.',
 true),

('young-adult', 'Young Adult', '1–3 years',
 'Settles into consistent personality. Full of energy and enthusiasm. Well-socialised dogs are reliable and predictable. May still have adolescent bursts of energy.',
 '2 meals per day of high-quality adult formula. Portion control to maintain ideal body condition score. No more puppy food — higher calorie density promotes obesity.',
 '45–60 minutes of vigorous exercise daily. Great age for advanced sports — agility, fetch, scent work, hiking.',
 ARRAY['dental disease if not brushed regularly', 'obesity from overfeeding', 'anxiety if under-stimulated'],
 'Best age to advance training — high energy, peak trainability. Solidify all basic commands. Address any problem behaviours now before they become entrenched habits.',
 ARRAY['excess energy without enough exercise', 'boredom-driven destruction', 'leash reactivity'],
 'Annual vet wellness checks. Dental scaling if recommended. Maintain consistent exercise and enrichment schedule. Introduce longer solo time to build independence.',
 true),

('adult', 'Adult', '3–7 years',
 'Calm, consistent temperament. Fully established personality. Strong bond with family. Reliable recall and command response in well-trained dogs.',
 '2 meals per day. Monitor weight closely — metabolism slows. Consider joint-supportive additives (glucosamine) for large breeds from age 5.',
 '30–45 minutes daily for most breeds. Tailor to individual energy level. Mental enrichment remains important.',
 ARRAY['weight gain', 'dental disease', 'early arthritis in large breeds', 'hypothyroidism'],
 'Maintain all training with regular practice. Introduce new enrichment activities to prevent boredom. Consider therapy dog training or canine sports.',
 ARRAY['weight gain', 'reduced play drive', 'emerging joint stiffness in large breeds'],
 'Annual vet wellness checks including bloodwork from age 5. Dental scaling as needed. Preventive joint supplements for large breeds. Keep up monthly tick and flea prevention.',
 true),

('senior-small', 'Senior (Small & Medium Breeds)', '8–12 years',
 'Slower to rise, longer naps, occasional confusion. May become more clingy or conversely more independent. Senses begin to dull. Still capable of enjoyment and play.',
 '2 smaller meals of senior formula. Reduced calories to prevent weight gain on lower activity. Higher protein to maintain muscle mass. Joint supplements. Fresh water always available.',
 '2–3 shorter walks daily rather than one long session. Low-impact activities — swimming is ideal. Mental enrichment as important as ever.',
 ARRAY['arthritis', 'dental disease', 'hypothyroidism', 'cognitive dysfunction', 'vision and hearing loss', 'kidney disease'],
 'Short, low-pressure refresher sessions maintain cognitive function. Never force exercise — let the dog set the pace. Mental puzzles and sniff games replace high-impact activities.',
 ARRAY['stiffness after rest', 'increased thirst/urination', 'house-training accidents', 'changes in sleep patterns'],
 'Bi-annual vet visits with comprehensive bloodwork. Orthopaedic dog bed. Ramp instead of stairs for sore joints. Keep routine consistent — seniors find change stressful.',
 true),

('senior-large', 'Senior (Large & Giant Breeds)', '6–10 years',
 'Large breeds age faster — a 7-year-old German Shepherd is equivalent to a 60-year-old human. Noticeable joint stiffness. Energy levels markedly reduced.',
 'Senior large-breed formula. Lower phosphorus to support kidneys. Omega-3 for joint inflammation. Maintain protein to prevent muscle wasting.',
 'Gentle daily walks of 20–30 minutes. Swimming and hydrotherapy excellent for arthritic joints. Never skip exercise entirely — movement prevents stiffness.',
 ARRAY['severe arthritis', 'degenerative myelopathy', 'cardiac disease', 'cancer', 'kidney disease', 'cognitive decline'],
 'Simple commands and sniff-based games keep the mind active without physical strain. Be patient with slower response times — hearing and vision may be failing.',
 ARRAY['difficulty rising', 'muscle wasting in hindquarters', 'exercise intolerance', 'weight loss'],
 'Bi-annual vet visits mandatory. Joint pain management (vet-prescribed anti-inflammatories). Orthopaedic bed essential. Non-slip mats on hard floors. Consider mobility aids for severe arthritis.',
 true),

('geriatric', 'Geriatric', '12+ years (small), 9+ years (large)',
 'Predominantly sleeps. May be disoriented at times (canine cognitive dysfunction). Needs warmth, quiet, and predictable routine. May show signs of dementia.',
 'Highly digestible senior food in small frequent meals. May need appetite stimulation. Hydration is critical — consider wet food to increase moisture intake.',
 'Gentle, short walks only as tolerated. Never force. A sniff around the garden may be enough.',
 ARRAY['multi-organ dysfunction', 'cancer', 'severe arthritis', 'canine cognitive dysfunction', 'incontinence', 'blindness', 'deafness'],
 'Routine and calm environment over new experiences. Cognitive enrichment through gentle sniff games. Let the dog choose activity levels each day.',
 ARRAY['incontinence', 'confusion and disorientation', 'loss of appetite', 'extreme lethargy', 'pain'],
 'Palliative care focus — quality of life over longevity. Regular pain assessments with vet. Consider hospice or end-of-life planning. Provide maximum comfort, warmth, and gentle affection.',
 true);


-- ────────────────────────────────────────────────────────────
-- TABLE 3: nutritional_guides (10 entries)
-- ────────────────────────────────────────────────────────────

INSERT INTO nutritional_guides (slug, title, category, description, recommended_foods, quantities_chart, foods_to_avoid, supplements_info, special_diets, transitions_guide, is_published) VALUES

('dry-kibble-guide', 'Complete Guide to Dry Kibble for Indian Dogs', 'food_types',
 'Dry kibble is the most convenient and widely available dog food in India. When chosen correctly, it provides complete balanced nutrition. This guide helps you choose the right kibble for your dog.',
 ARRAY['real meat as first ingredient (chicken, lamb, fish)', 'whole grains (brown rice, oats)', 'vegetables (sweet potato, peas)', 'omega-3 sources (fish meal, flaxseed)'],
 '{"puppies": {"meals_per_day": 3, "grams_per_meal": "80-150g depending on breed size", "notes": "Use puppy-specific formula"}, "adults": {"meals_per_day": 2, "grams_per_meal": "150-300g depending on weight", "notes": "Adjust for activity level"}, "seniors": {"meals_per_day": 2, "grams_per_meal": "120-250g", "notes": "Switch to senior formula at 7 years"}}',
 ARRAY['corn or wheat as first ingredient', 'artificial preservatives (BHA, BHT)', 'by-product meal without specification', 'excessive fillers'],
 'No supplements required if feeding a complete and balanced AAFCO or BIS-certified kibble. Adding Omega-3 fish oil (1000mg per 10kg body weight) improves coat health in Indian humidity.',
 ARRAY['grain-free (for dogs with grain allergies)', 'limited ingredient diets (for sensitive stomachs)', 'large-breed specific (controlled calcium)'],
 'When switching brands, mix 25% new food with 75% old for 3 days. Then 50/50 for 3 days. Then 75% new for 3 days. Full transition by day 10. Abrupt changes cause diarrhoea.',
 true),

('homemade-indian-dog-food', 'Homemade Dog Food: Indian Kitchen Guide', 'food_types',
 'Many Indian dog parents prefer homemade food. When done correctly, it can be nutritious and cost-effective. This guide covers safe Indian ingredients and preparation methods.',
 ARRAY['boiled chicken (boneless)', 'boiled eggs', 'brown rice', 'boiled sweet potato', 'boiled carrots and green beans', 'paneer (in moderation)', 'curd/yogurt (plain, unsweetened)', 'fish (sardines, rohu — cooked, boneless)'],
 '{"puppies": {"meals_per_day": 3, "notes": "2-3% of expected adult body weight daily, split across meals"}, "adults": {"meals_per_day": 2, "notes": "2-2.5% of current body weight daily"}, "seniors": {"meals_per_day": 2, "notes": "Reduce carbs, increase protein to maintain muscle"}}',
 ARRAY['onion and garlic (toxic)', 'grapes and raisins (toxic)', 'raw or cooked bones (choking hazard)', 'spices (all)', 'salt', 'ghee or oil in large quantities', 'maida and refined flour', 'sugar and jaggery'],
 'Homemade diets are almost always deficient in calcium, zinc, and Vitamin D. A veterinary-approved supplement powder (e.g., Pet-Cal or similar) must be added to every meal. Consult a vet nutritionist for exact quantities.',
 ARRAY['rotation diet (rotate protein sources weekly)', 'elimination diet (for allergy identification)'],
 'Transition slowly over 10 days. Watch for soft stool, flatulence, or vomiting during transition. Keep a food diary to track any reactions.',
 true),

('raw-barf-diet', 'Raw Feeding (BARF Diet) for Dogs', 'food_types',
 'Biologically Appropriate Raw Food (BARF) mimics a dog''s ancestral diet. Growing in popularity in India among informed pet owners. Requires careful planning to avoid nutritional imbalances and pathogen risk.',
 ARRAY['raw meaty bones (chicken necks, wings)', 'muscle meat (chicken, mutton, beef)', 'organ meat (liver, kidney) — 10% of diet', 'raw eggs', 'leafy vegetables (10% of diet)', 'fish (sardines, mackerel)'],
 '{"adults": {"percentage_of_body_weight": "2-3%", "breakdown": "70% muscle meat, 10% raw edible bone, 10% organs (5% liver), 10% vegetables", "notes": "Introduce organs slowly to avoid loose stool"}}',
 ARRAY['cooked bones of any kind (splinter hazard)', 'onion, garlic, grapes', 'pork (high parasite risk in India)', 'farmed fish with high mercury'],
 'Raw diets are typically calcium-balanced through raw edible bone. Add fish oil (Omega-3). Kelp powder provides iodine and trace minerals. Consult a raw feeding specialist or vet before starting.',
 ARRAY['prey model raw (PMR)', 'BARF'],
 'Start with a single protein source (chicken) for 2–3 weeks. Add one new ingredient at a time. Monitor stool — raw-fed dogs typically produce smaller, firmer, less odorous stools.',
 true),

('puppy-feeding-schedule', 'Puppy Feeding Schedule & Quantities', 'feeding_schedules',
 'Puppies have entirely different nutritional needs from adult dogs. Getting feeding right in the first year shapes lifelong health. This guide covers quantities, frequency, and food selection by age.',
 ARRAY['puppy-formula kibble (AAFCO or BIS certified)', 'puppy-specific wet food', 'boiled chicken and rice (homemade option)'],
 '{"8-12_weeks": {"meals_per_day": 4, "cups_per_meal": "0.25-0.5 depending on breed size"}, "3-6_months": {"meals_per_day": 3, "cups_per_meal": "0.5-1 cup"}, "6-12_months": {"meals_per_day": 2, "cups_per_meal": "1-1.5 cups"}}',
 ARRAY['adult dog food', 'food intended for humans', 'raw food without veterinary guidance', 'supplements without vet approval'],
 'Calcium and phosphorus supplementation is NOT needed on a complete puppy kibble — over-supplementation causes severe bone problems in large breeds. Only supplement if feeding homemade food.',
 ARRAY['large-breed puppy formula (controlled calcium)', 'small-breed puppy formula (higher caloric density)'],
 'Use the manufacturer guidelines as a starting point, then adjust based on body condition. You should be able to feel ribs easily but not see them. Review quantities monthly as the puppy grows.',
 true),

('adult-feeding-schedule', 'Adult Dog Feeding Guide: Portions & Timing', 'feeding_schedules',
 'Most adult dogs thrive on two meals per day. This guide covers how to calculate correct portions based on body weight, activity level, and whether the dog is spayed/neutered.',
 ARRAY['adult formula kibble', 'lean protein sources', 'fibre-rich vegetables as toppers'],
 '{"small_breeds_under_10kg": {"meals_per_day": 2, "daily_grams": "100-200g dry food"}, "medium_breeds_10-25kg": {"meals_per_day": 2, "daily_grams": "200-350g dry food"}, "large_breeds_over_25kg": {"meals_per_day": 2, "daily_grams": "350-600g dry food"}, "notes": "Spayed/neutered dogs need 25% fewer calories"}',
 ARRAY['free-feeding (leaving food out all day)', 'human leftovers as main diet', 'more than 10% treats of daily caloric intake'],
 'Joint supplements (glucosamine + chondroitin) for large breeds over 5 years. Omega-3 fish oil for coat health in Indian climate. Probiotics for dogs with sensitive stomachs.',
 ARRAY['weight management formula (for overweight dogs)', 'sensitive stomach formula'],
 'If changing adult food brands, follow the 10-day transition protocol: 25/75 → 50/50 → 75/25 → 100% new food over 10 days.',
 true),

('foods-to-avoid-india', 'Foods That Are Toxic or Harmful to Dogs', 'foods_to_avoid',
 'Many common Indian kitchen ingredients are toxic to dogs. Sharing food from the table is a natural impulse but can cause serious illness or death. Learn what to avoid.',
 ARRAY[]::text[],
 '{}',
 ARRAY['onion and garlic (destroy red blood cells — all forms including powder)', 'grapes and raisins (kidney failure even in tiny amounts)', 'chocolate (theobromine toxicity)', 'xylitol (artificial sweetener — causes liver failure)', 'macadamia nuts', 'avocado (persin toxicity)', 'raw yeast dough', 'alcohol', 'caffeine', 'cooked bones (splinter risk)', 'raw pork and wild boar (trichinosis risk)', 'salty snacks', 'spicy food'],
 NULL,
 ARRAY[]::text[],
 'If you suspect your dog has eaten a toxic food, call your vet immediately. Do not induce vomiting without veterinary instruction. Keep the AWBI helpline number saved: 1962.',
 true),

('weight-management-diet', 'Weight Management & Obesity in Dogs', 'special_diets',
 'Obesity is the most common preventable disease in Indian dogs. Overfeeding, excess treats, and table scraps are the primary causes. Here''s how to get your dog back to a healthy weight safely.',
 ARRAY['high-protein low-fat kibble', 'green beans (as low-calorie filler)', 'carrots (as treats instead of biscuits)', 'cucumber slices', 'boiled boneless chicken breast'],
 '{"overweight_dogs": {"caloric_reduction": "Reduce current intake by 20-25%", "meals_per_day": 3, "notes": "More frequent smaller meals reduce hunger. Weigh food — do not estimate by cups"}}',
 ARRAY['all treats except vegetables', 'table scraps', 'high-fat foods', 'excess carbohydrates', 'dental chews (high calorie)'],
 'Omega-3 supplementation (fish oil) supports metabolism. L-carnitine helps convert fat to energy — ask your vet about dosing. No supplements will replace caloric restriction.',
 ARRAY['prescription weight loss diet', 'high-fibre satiety formula'],
 'Target 1–2% body weight loss per week — faster loss causes muscle wasting. Weigh your dog monthly. Increase exercise gradually alongside dietary changes.',
 true),

('senior-dog-nutrition', 'Senior Dog Nutrition Guide', 'special_diets',
 'Nutritional needs change significantly as dogs age. Senior dogs need fewer calories but more of specific nutrients. This guide covers the dietary shifts needed after age 7 (small breeds) or age 5 (large breeds).',
 ARRAY['senior-formula kibble', 'easily digestible proteins (fish, eggs, chicken)', 'joint-supporting foods (fish with omega-3)', 'fibre-rich vegetables'],
 '{"seniors": {"caloric_reduction": "20-30% fewer calories than adult peak", "meals_per_day": 2, "notes": "Smaller, more frequent meals easier to digest. Wet food or mixed diet helps hydration."}}',
 ARRAY['excess sodium (kidney stress)', 'very high phosphorus foods (kidney disease risk)', 'hard dry treats (dental pain)', 'rich fatty foods (pancreatitis risk)'],
 'Glucosamine and chondroitin for joint health. Omega-3 fish oil for inflammation. Probiotics for digestive health. Antioxidants (Vitamin E, C) for cognitive support. Discuss all supplements with vet before starting.',
 ARRAY['renal diet (for kidney disease)', 'cardiac diet (for heart disease)', 'diabetic diet'],
 'Transition to senior food when recommended by vet. Mix old and new over 14 days — senior dogs have more sensitive digestion than adults.',
 true),

('supplements-guide', 'Dog Supplements Guide for Indian Conditions', 'supplements',
 'India''s climate, endemic diseases (tick fever, mange), and local food options create specific supplementation needs. This guide covers the most useful supplements for Indian dogs with evidence-based reasoning.',
 ARRAY[]::text[],
 '{}',
 ARRAY[]::text[],
 'OMEGA-3 FISH OIL: Reduces skin inflammation from allergies and humidity-related dermatitis. 1000mg per 10kg body weight daily. PROBIOTICS: Especially useful during monsoon season when water quality drops. GLUCOSAMINE+CHONDROITIN: Essential for large breeds from age 4–5. CALCIUM SUPPLEMENT: Only for dogs on homemade food — never add to commercial kibble. TICK PREVENTION: Not a supplement but critical — use vet-recommended spot-on or tick collar year-round. B-COMPLEX: Supports energy metabolism and coat health in dogs with poor appetites.',
 ARRAY['homemade diet supplementation', 'post-illness recovery protocols'],
 'Always introduce supplements one at a time, spaced 1 week apart, to identify any adverse reactions. Never exceed vet-recommended doses — more is not better.',
 true),

('vegetarian-dog-diet', 'Vegetarian Dog Diet in India', 'special_diets',
 'Some Indian families prefer a vegetarian diet for their dogs for religious or ethical reasons. Dogs are omnivores and can technically survive on a plant-based diet, though it requires very careful planning to avoid deficiencies.',
 ARRAY['paneer (high protein)', 'curd/yogurt (plain)', 'lentils (well-cooked)', 'chickpeas (well-cooked)', 'tofu', 'brown rice', 'sweet potato', 'leafy vegetables'],
 '{"adults": {"notes": "Vegetarian dogs need higher total food volume to meet protein needs. Consider a commercial vegetarian kibble as base."}}',
 ARRAY['raw legumes (toxic uncooked)', 'onion and garlic', 'spiced or seasoned dals', 'excess fat from dairy'],
 'Vegetarian diets are typically deficient in: Vitamin B12, Taurine, L-carnitine, Vitamin D3, Zinc, and complete amino acid profiles. A vet-prescribed supplement covering all these deficiencies is non-negotiable on a vegetarian diet.',
 ARRAY['vegan diet', 'lacto-vegetarian diet'],
 'If transitioning an existing meat-eater to vegetarian, do so over 3–4 weeks. Monitor energy levels, coat quality, and stool consistency closely. Bloodwork at 3 months after transition.',
 true);


-- ────────────────────────────────────────────────────────────
-- TABLE 4: health_conditions (10 entries)
-- ────────────────────────────────────────────────────────────

INSERT INTO health_conditions (slug, name, severity, description, symptoms, when_to_see_vet, home_remedies, prevention_tips, affected_breeds, vaccinations_needed, is_published) VALUES

('parvovirus', 'Canine Parvovirus (Parvo)', 'severe',
 'Parvovirus is a highly contagious, life-threatening viral disease that attacks the digestive system of unvaccinated dogs. It is widespread across India and is one of the leading causes of death in unvaccinated puppies.',
 ARRAY['severe bloody diarrhoea', 'vomiting', 'lethargy', 'loss of appetite', 'fever then hypothermia', 'dehydration', 'abdominal pain'],
 'EMERGENCY: Rush to vet immediately. Do not wait. Parvo can kill a puppy in 48–72 hours without treatment. Every hour matters.',
 'There are no effective home remedies for Parvo. IV fluids, anti-nausea medication, and antibiotics (to prevent secondary infection) require hospitalisation. Do not attempt home treatment.',
 ARRAY['Vaccinate on schedule (6, 9, 12 weeks then annual boosters)', 'Do not take unvaccinated puppies to public areas', 'Avoid contact with unknown dogs until fully vaccinated', 'Parvovirus survives in soil for up to a year — disinfect with 1:30 bleach solution'],
 ARRAY['Labrador Retriever', 'Rottweiler', 'German Shepherd', 'Doberman Pinscher'],
 ARRAY['Parvovirus — core vaccine (given as part of 5-in-1 or 7-in-1 combination)'],
 true),

('tick-fever-ehrlichiosis', 'Tick Fever (Ehrlichiosis / Babesiosis)', 'severe',
 'Tick fever is one of the most common and serious diseases in Indian dogs, caused by tick-borne parasites. Ehrlichiosis and Babesiosis are the two most common types. Both can be fatal without prompt treatment.',
 ARRAY['sudden high fever (39.5°C+)', 'lethargy and weakness', 'loss of appetite', 'pale or yellow gums', 'nosebleeds or unusual bleeding', 'swollen lymph nodes', 'difficulty breathing in severe cases'],
 'See a vet within 24 hours of fever onset. Blood test (CBC and blood smear) required for diagnosis. Early treatment with doxycycline is highly effective — delayed treatment leads to organ damage.',
 'Cool the dog with damp towels if fever is very high while rushing to vet. Ensure adequate hydration. There are no effective home remedies — antibiotics are essential.',
 ARRAY['Use vet-recommended tick prevention year-round (spot-on, tick collar, or tablet)', 'Check for ticks after every outdoor walk', 'Remove ticks within 24 hours using tick tweezers — never crush with fingers', 'Treat environment (kennel, garden) with tick spray'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 true),

('mange-sarcoptic', 'Sarcoptic Mange (Scabies)', 'moderate',
 'Sarcoptic mange is a highly contagious skin disease caused by the mite Sarcoptes scabiei. Very common in India, especially in street dogs. Causes intense itching and can spread to humans.',
 ARRAY['intense itching (especially at night)', 'hair loss (starting at ear edges, elbows, belly)', 'red, crusty skin', 'thickened skin over time', 'secondary skin infections from scratching', 'weight loss in severe cases'],
 'See a vet for diagnosis (skin scraping test). Treatment requires prescription anti-mite medication — ivermectin injection or selamectin spot-on. Do not attempt home treatment as it requires accurate diagnosis and dosing.',
 'Keep affected area clean and dry. An Elizabethan collar prevents the dog from worsening skin through scratching. Wash all bedding in hot water and quarantine from other pets and children.',
 ARRAY['Avoid contact with stray or unknown dogs', 'Treat all pets in the household simultaneously', 'Maintain good skin health with Omega-3 supplementation', 'Annual vet check-ups for early detection'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 true),

('hip-dysplasia', 'Hip Dysplasia', 'moderate',
 'Hip dysplasia is a genetic condition where the hip joint develops abnormally, causing pain and arthritis. Extremely common in large and giant breeds. India''s humidity and temperature worsen joint inflammation.',
 ARRAY['difficulty rising from rest', 'bunny-hopping gait', 'reluctance to exercise', 'crying when touched on hips', 'muscle wasting in hindquarters', 'limping after exercise'],
 'See a vet when you notice any gait abnormality or exercise intolerance. X-ray confirms diagnosis. Early intervention (weight management, physiotherapy, medication) dramatically improves quality of life.',
 'Maintain a healthy weight — every excess kilogram dramatically worsens hip dysplasia. Gentle, low-impact exercise (swimming) keeps muscles supporting the joint. Omega-3 supplements reduce inflammation.',
 ARRAY['Choose puppies from OFA/hip-certified parents', 'Avoid over-exercise of puppies before growth plates close', 'Maintain lean body weight lifelong', 'Start joint supplements (glucosamine) at age 4–5 for at-risk breeds'],
 ARRAY['German Shepherd', 'Labrador Retriever', 'Golden Retriever', 'Rottweiler', 'Boxer'],
 ARRAY[]::text[],
 true),

('skin-allergies-atopy', 'Skin Allergies (Atopic Dermatitis)', 'mild',
 'Allergic skin disease is the most common skin problem in Indian dogs, worsened by high humidity, dust mites, and pollen. Dogs scratch, lick, and chew constantly, leading to secondary infections.',
 ARRAY['constant licking of paws', 'rubbing face on floor', 'red, inflamed skin (especially paws, belly, ears, face)', 'recurrent ear infections', 'hair loss from scratching', 'foul smell from skin folds'],
 'See a vet if symptoms are moderate to severe, if secondary infection is suspected, or if home management fails. Allergy testing and immunotherapy may be recommended for severe cases.',
 'Bathe with vet-recommended oatmeal or medicated shampoo weekly. Wipe paws after every outdoor walk to remove allergens. Omega-3 supplementation strengthens the skin barrier. Anti-histamines (cetirizine) may provide temporary relief — confirm dosing with vet.',
 ARRAY['Identify and minimise allergen exposure', 'Regular bathing to remove environmental allergens', 'High-quality diet to support skin barrier function', 'Keep home dust-mite free — wash dog beds weekly in hot water', 'Omega-3 supplementation from puppyhood for at-risk breeds'],
 ARRAY['Labrador Retriever', 'Golden Retriever', 'Beagle', 'Shih Tzu', 'Boxer'],
 ARRAY[]::text[],
 true),

('dental-disease', 'Dental Disease (Periodontal Disease)', 'moderate',
 'By age 3, 80% of dogs show signs of dental disease. In India, where dental care is rarely considered, most dogs suffer quietly. Untreated dental disease causes pain, tooth loss, and can damage the heart and kidneys.',
 ARRAY['bad breath (halitosis)', 'yellow or brown tartar on teeth', 'red, swollen, or bleeding gums', 'reluctance to eat hard food', 'pawing at mouth', 'dropping food while eating', 'visible tooth root exposure'],
 'See a vet when you notice tartar buildup, bad breath, or changes in eating habits. Dental scaling under anaesthesia is the gold standard treatment.',
 'Daily tooth brushing with dog-safe toothpaste is the most effective home prevention. Dental chews, water additives, and dental toys help but do not replace brushing. Avoid human toothpaste — xylitol is toxic to dogs.',
 ARRAY['Daily tooth brushing from puppyhood', 'Annual vet dental check-up', 'Professional scaling when recommended', 'Dental health kibble or water additives as adjuncts'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 true),

('heat-stroke', 'Heat Stroke (Hyperthermia)', 'severe',
 'India''s summers are dangerous for dogs, particularly in cities like Delhi, Nagpur, and Chennai. Dogs cannot sweat and rely on panting to cool down. Heat stroke can cause brain damage and death within minutes.',
 ARRAY['heavy, rapid panting', 'drooling excessively', 'bright red gums', 'vomiting', 'diarrhoea', 'confusion or disorientation', 'collapse', 'seizures in severe cases'],
 'EMERGENCY: This is a life-threatening emergency. Cool the dog with room-temperature (not ice cold) water while rushing to the vet. Never use ice — it constricts blood vessels and worsens the situation.',
 'Move to shade or air conditioning immediately. Apply cool wet towels to neck, armpits, and groin. Offer small sips of cool water — do not force. Fan the dog while keeping wet. Rectal temperature below 39.5°C is the target. Continue cooling until vet is reached.',
 ARRAY['Never leave a dog in a parked car even for 2 minutes', 'Exercise only in early morning or after sunset in summer', 'Always provide shade and fresh cool water', 'Know your breed risk — brachycephalic and thick-coated breeds are highest risk', 'Use cooling vests or damp towels during outdoor activity'],
 ARRAY['Pomeranian', 'Shih Tzu', 'Boxer', 'Golden Retriever', 'any thick-coated breed'],
 ARRAY[]::text[],
 true),

('leptospirosis', 'Leptospirosis', 'severe',
 'Leptospirosis is a bacterial disease spread through water and soil contaminated with infected animal urine — particularly relevant during India''s monsoon season. Can infect humans (zoonotic). Preventable by vaccine.',
 ARRAY['sudden fever', 'muscle pain and reluctance to move', 'vomiting and diarrhoea', 'excessive thirst and urination', 'yellowing of eyes and skin (jaundice)', 'blood in urine', 'kidney and liver failure in severe cases'],
 'See a vet immediately if you notice jaundice (yellow tinge to eyes/skin/gums), sudden kidney or liver symptoms, or fever during or after monsoon season.',
 'No effective home treatment. Antibiotics (doxycycline or penicillin) are the treatment — requires prescription. Keep the dog well-hydrated while seeking veterinary care.',
 ARRAY['Vaccinate annually — especially critical in monsoon-prone areas', 'Avoid letting dogs drink from puddles, ponds, or floodwater', 'Avoid areas frequented by rats, especially during monsoon', 'Wash hands after handling a potentially infected dog — leptospirosis is zoonotic'],
 ARRAY[]::text[],
 ARRAY['Leptospirosis vaccine (part of some combination vaccines — confirm with vet)'],
 true),

('bloat-gdv', 'Bloat (Gastric Dilatation-Volvulus)', 'severe',
 'Bloat is a life-threatening condition where the stomach fills with gas and twists on itself, cutting off blood supply. Most common in large, deep-chested breeds. Death can occur within hours without emergency surgery.',
 ARRAY['swollen, distended abdomen', 'unproductive retching (trying to vomit with nothing coming up)', 'excessive drooling', 'restlessness and inability to settle', 'pale gums', 'rapid heartbeat', 'collapse'],
 'EMERGENCY: Rush to emergency vet immediately. Do not wait to see if it improves. GDV is always fatal without surgical intervention. Time is critical — every 30 minutes reduces survival rate.',
 'There is no home treatment for GDV. This is strictly a surgical emergency.',
 ARRAY['Feed 2–3 small meals instead of one large meal', 'Do not exercise 1 hour before or 2 hours after eating', 'Use a slow feeder bowl to reduce gulping', 'Avoid raised food bowls (contrary to older advice — research shows raised bowls increase risk)', 'Prophylactic gastropexy (stomach stapling) recommended during spay/neuter for high-risk breeds'],
 ARRAY['German Shepherd', 'Rottweiler', 'Doberman Pinscher', 'Boxer', 'Great Dane'],
 ARRAY[]::text[],
 true),

('ear-infection-otitis', 'Ear Infection (Otitis Externa)', 'mild',
 'Ear infections are extremely common in India due to humidity and the prevalence of floppy-eared breeds. Left untreated, they progress to middle and inner ear infections, causing permanent hearing damage.',
 ARRAY['shaking head frequently', 'scratching at one or both ears', 'foul odour from ears', 'brown or black discharge in ear canal', 'redness and swelling of ear flap', 'tilting head to one side', 'crying when ears are touched'],
 'See a vet when you notice discharge, odour, or persistent head shaking. A swab test identifies whether the infection is bacterial, yeast, or mite-related — each requires different treatment.',
 'Gently clean the outer ear with a vet-recommended ear cleaner and cotton ball — never cotton swabs inside the canal. Do not use home remedies (oil, vinegar) without veterinary guidance as they can worsen infections.',
 ARRAY['Clean ears weekly with vet-recommended cleaner', 'Dry ears thoroughly after bathing or swimming', 'Maintain regular grooming — excess ear hair traps moisture', 'Address underlying allergies which predispose to ear infections'],
 ARRAY['Labrador Retriever', 'Beagle', 'Golden Retriever', 'Shih Tzu', 'Pomeranian'],
 ARRAY[]::text[],
 true);


-- ────────────────────────────────────────────────────────────
-- TABLE 5: behavioral_topics (10 entries)
-- ────────────────────────────────────────────────────────────

INSERT INTO behavioral_topics (slug, name, applicable_stages, issue_description, causes, solutions, training_techniques, do_and_donts, common_mistakes, external_resources, is_published) VALUES

('excessive-barking', 'Excessive Barking', ARRAY['puppy', 'adult', 'senior'],
 'Excessive barking is one of the most common complaints from dog owners and their neighbours in Indian apartments. While all dogs bark, compulsive or triggered barking can strain family relationships and cause neighbour conflicts.',
 ARRAY['boredom and under-stimulation', 'territorial behaviour (common in guard breeds)', 'fear or anxiety response', 'attention-seeking behaviour reinforced by owners', 'separation anxiety', 'cognitive dysfunction in seniors'],
 'Identify the specific trigger for barking before attempting to modify the behaviour. Boredom barking requires more exercise and enrichment. Alert barking needs desensitisation. Attention-barking requires ignoring the behaviour completely and rewarding quiet.',
 ARRAY['"Quiet" command: Wait for a pause in barking, immediately mark with "Yes!" and reward. Build duration of quiet gradually.', 'Desensitisation: For trigger-based barking, expose the dog to the trigger at sub-threshold distance while rewarding calm behaviour.', 'Management: Block visual access to triggers (window film, baby gates) while training.', '"Look at that" game: Teach the dog to look at a trigger, look back at you, get a treat — changes the emotional response.'],
 '{"dos": ["identify and address the root cause first", "reward quiet and calm behaviour proactively", "provide adequate physical and mental exercise", "use puzzle feeders and enrichment toys", "be consistent — all family members must follow the same rules"], "donts": ["shout at the dog to stop barking — this reinforces the behaviour", "use punishment-based tools (shock collars, citronella collars)", "comfort the dog during fear-barking without working to change the emotion", "give attention when the dog barks for attention", "assume the dog will just grow out of it"]}',
 ARRAY['Shouting "Quiet!" while the dog is barking — this is interpreted as joining in', 'Giving treats to distract from barking — this rewards the barking', 'Inconsistent rules across family members', 'Not providing enough exercise — a tired dog barks far less'],
 '{"links": [{"title": "ASPCA Barking Guide", "url": "https://www.aspca.org/pet-care/dog-care/common-dog-behavior-issues/barking"}, {"title": "Patricia McConnell on Barking", "url": "https://www.patriciamcconnell.com"}], "books": ["The Other End of the Leash by Patricia McConnell", "Barking: The Sound of a Language by Turid Rugaas"]}',
 true),

('leash-pulling', 'Leash Pulling', ARRAY['puppy', 'adult'],
 'Leash pulling is one of the most physically challenging behaviour problems for owners, and one of the most common reasons dogs are given up in India. A 30kg Labrador pulling can cause falls and injuries in owners of all ages.',
 ARRAY['never having been taught to walk on a loose leash', 'environment is more exciting than the owner', 'owner has inadvertently reinforced pulling by following the dog', 'insufficient exercise before walks — too much pent-up energy', 'wrong equipment (collar only, no back-clip harness for strong dogs)'],
 'Leash manners must be taught — dogs do not naturally understand that pulling is undesirable. The most effective method is the "be a tree" technique combined with rewarding any moment of loose leash. Use a front-clip harness or head halter for management while training.',
 ARRAY['"Be a tree": The moment the leash goes tight, stop completely. When the dog looks back or moves to release tension, mark "Yes!" and reward. Resume walking.', '"Change direction": When the dog pulls, turn 180° and walk the other way without saying a word. The dog learns that pulling means going backwards.', '"Engage and reward": Keep treats in hand during walks and reward frequently for choosing to stay near you.', '"1 2 3 Magic": Count 1-2-3 whenever leash is loose, treat. Builds connection between loose leash and reward.'],
 '{"dos": ["use a front-clip harness to reduce pulling force while training", "reward frequently for loose leash — every 3-5 steps at first", "keep training sessions short (5-10 min) on walks", "be consistent every single walk", "exercise the dog before a training walk to reduce excitement"], "donts": ["yank or jerk the leash", "allow the dog to reach its destination while pulling — this rewards the pull", "use a retractable leash during training", "expect improvement in one session — this takes weeks", "get frustrated and stop — consistency is everything"]}',
 ARRAY['Using a retractable leash — this teaches the dog that pulling extends their range', 'Letting the dog sniff or greet people as a reward while pulling', 'Inconsistency — allowing pulling when in a hurry'],
 '{"links": [{"title": "Kikopup Loose Leash Walking", "url": "https://www.youtube.com/user/kikopup"}, {"title": "Zak George Leash Training", "url": "https://www.youtube.com/c/ZakGeorge"}], "books": ["Loose Leash Walking by Terry Ryan", "How to Behave So Your Dog Behaves by Sophia Yin"]}',
 true),

('separation-anxiety', 'Separation Anxiety', ARRAY['puppy', 'adult'],
 'Separation anxiety is a serious condition in which dogs experience extreme distress when left alone. In India, where families historically kept dogs with someone at home at all times, this is increasingly common as lifestyles change.',
 ARRAY['sudden change in routine (return to office after working from home)', 'rehoming or shelter history', 'never having been taught to be alone', 'over-bonding with one family member', 'insufficient exercise and mental stimulation', 'genetic predisposition in some breeds'],
 'True separation anxiety requires a systematic desensitisation and counterconditioning programme — often with the help of a certified behaviourist. The core principle is to keep departures below the anxiety threshold and very gradually increase alone time.',
 ARRAY['"Alone time training": Begin with 1-second absences, building to 5 seconds, 30 seconds, 1 minute, 5 minutes over weeks. Never progress faster than the dog can handle.', '"Pre-departure cues desensitisation": Pick up keys, put on shoes, get bag — without leaving. Repeat until these cues cause no anxiety.', '"Kong departure protocol": Reserve a high-value stuffed Kong exclusively for departures to create a positive association.', '"Safe space training": Teach the dog that their bed or crate is a calm, happy place long before they need to be alone there.'],
 '{"dos": ["work with a certified animal behaviourist for severe cases", "exercise the dog before alone periods", "provide enrichment (stuffed kongs, licki mats) for departure", "build alone time gradually and systematically", "consider pheromone diffusers (Adaptil) as a supplement to training"], "donts": ["make departures and arrivals emotional", "punish the dog for destruction during alone time — it is anxiety, not spite", "get a second dog to fix separation anxiety — it rarely works", "use flooding (leaving for long periods) to force adaptation — this worsens anxiety", "crate a dog with separation anxiety without proper training — it escalates panic"]}',
 ARRAY['Getting a second dog to solve the problem (can work for mild cases, worsens severe ones)', 'Soothing the dog excessively before leaving (increases anxiety)', 'Punishing post-departure destruction (the dog cannot connect the punishment to the event)'],
 '{"links": [{"title": "ASPCA Separation Anxiety Guide", "url": "https://www.aspca.org/pet-care/dog-care/common-dog-behavior-issues/separation-anxiety"}, {"title": "Malena DeMartini (Separation Anxiety Specialist)", "url": "https://malenademartini.com"}], "books": ["Treating Separation Anxiety in Dogs by Malena DeMartini-Price", "I''ll Be Home Soon by Patricia McConnell"]}',
 true),

('aggression-toward-strangers', 'Aggression Toward Strangers', ARRAY['adult'],
 'Aggression toward unfamiliar people is one of the most concerning behaviour problems and a leading reason dogs are euthanised in India. It is almost always rooted in fear, not dominance. Understanding this is the foundation of treatment.',
 ARRAY['inadequate socialisation before 16 weeks', 'traumatic experience with strangers', 'fear response that escalated due to lack of support', 'genetic predisposition in guarding breeds', 'pain or medical cause (always rule out first)', 'owner''s own anxious or aggressive energy on the leash'],
 'Aggression is a veterinary and behavioural issue — a full vet check to rule out pain is the first step. Working with a certified behaviourist using positive-based counterconditioning is the evidence-based approach. Management to prevent bites must be immediate.',
 ARRAY['"Look at that" game: Teach the dog to see a stranger, look at you, and receive a treat — changing the emotional response from fear to anticipation of food.', '"BAT (Behaviour Adjustment Training)": Allow the dog to investigate at their chosen pace and retreat when they choose. This builds confidence and reduces fear.', '"Counter-conditioning": Every time a stranger appears at a distance, rain treats on the dog. Stranger = great things.'],
 '{"dos": ["seek professional help from a certified behaviourist (CPDT-KA, IAABC)", "use a properly fitted muzzle for safety during management — muzzles are not cruel", "always advocate for your dog — do not let strangers approach a fearful dog", "manage the environment while working on behaviour modification", "reward calm and relaxed body language proactively"], "donts": ["force the dog to interact with strangers to socialise them", "punish growling — this removes the warning sign before a bite", "alpha roll or use dominance-based techniques — these worsen fear aggression", "ignore the problem hoping it will resolve", "allow children near an aggressive dog without constant supervision"]}',
 ARRAY['Punishing growling (removes the warning sign — increases bite risk)', 'Forcing interaction with strangers (worsens fear)', 'Dismissing early warning signs as "just being protective"'],
 '{"links": [{"title": "IAABC Find a Behaviourist", "url": "https://iaabc.org/consultants"}, {"title": "Fear Free Happy Homes", "url": "https://fearfreehappyhomes.com"}], "books": ["Aggression in Dogs by Brenda Aloff", "The Culture Clash by Jean Donaldson"]}',
 true),

('potty-training', 'Potty Training', ARRAY['puppy'],
 'Potty training is typically the first major challenge for new dog owners in India. Apartment living with no garden access requires a systematic approach. Most puppies can be reliably house-trained by 4–6 months with consistency.',
 ARRAY['puppy''s small bladder cannot hold urine for more than 2–3 hours', 'inadequate supervision inside the home', 'inconsistent schedule', 'punishment-based approach creates fear around elimination near owners', 'inappropriate use of indoor pee pads long-term'],
 'Puppies need to eliminate after waking, after eating, after play, and roughly every 2 hours. The key is preventing accidents and rewarding success in the right spot — never punishing accidents after the fact.',
 ARRAY['"Umbilical cord training": Keep the puppy attached to you on a leash indoors so you never miss signs (sniffing, circling).', '"Scheduled bathroom breaks": Take puppy to the toilet spot every 2 hours and after every meal/play/nap.', '"Mark and reward": The moment the puppy finishes eliminating in the right spot, say "Yes!" and give a treat. Do not wait until you return inside.', '"Crate training": A correctly sized crate (puppy cannot stand and turn) prevents elimination while unsupervised — dogs naturally do not soil their sleeping area.'],
 '{"dos": ["take the puppy outside first thing in the morning and last thing at night", "reward immediately after elimination in the right place", "supervise constantly or use a crate when you cannot watch", "clean accidents with enzymatic cleaner to remove scent completely", "be patient — setbacks are normal"], "donts": ["punish accidents after the fact — the puppy cannot connect the punishment to the event", "rub the puppy''s nose in accidents — this is cruel and counterproductive", "use pee pads long-term if the goal is outdoor toileting — it teaches inside elimination", "give the puppy free roam of the house before reliable training", "yell or express anger around the puppy during bathroom breaks — creates anxiety"]}',
 ARRAY['Using punishment for accidents after the fact (puppy cannot connect punishment to earlier event)', 'Rubbing nose in accident (outdated, cruel, and ineffective)', 'Giving free roam before reliable training is established'],
 '{"links": [{"title": "AKC Puppy Potty Training Guide", "url": "https://www.akc.org/expert-advice/training/basics/puppy-house-training-basics/"}, {"title": "Kikopup Crate Training", "url": "https://www.youtube.com/watch?v=5FBm0g_rRzo"}], "books": ["Before and After Getting Your Puppy by Ian Dunbar"]}',
 true),

('destructive-chewing', 'Destructive Chewing', ARRAY['puppy', 'adult'],
 'Destructive chewing is a leading cause of property damage in Indian homes and a major source of conflict between dog owners and their families. It is almost always preventable with proper management and enrichment.',
 ARRAY['teething pain in puppies (3–7 months)', 'boredom and lack of mental stimulation', 'separation anxiety', 'attention-seeking behaviour', 'natural scavenging instinct not redirected to appropriate outlets', 'insufficient appropriate chew items'],
 'Management first: remove access to chewable items you do not want destroyed. Simultaneously, provide a rich variety of appropriate chew options. Redirect when you catch the dog chewing something inappropriate — never punish after the fact.',
 ARRAY['"Redirect, not punish": When you see the dog chewing something inappropriate, calmly interrupt and offer an appropriate chew toy. Reward when they take it.', '"Rotation of toys": Keep 10–15 toys and rotate 4–5 at a time. Novel objects are more interesting.', '"Food enrichment": Stuffed Kongs, licki mats, sniff mats, and puzzle feeders occupy the mind and redirect chewing energy.', '"Confinement training": Use a crate, playpen, or puppy-proofed room when you cannot supervise.'],
 '{"dos": ["puppy-proof the home — prevention is easier than correction", "provide at least 3 different types of chews (hard, soft, edible)", "exercise before leaving the dog alone", "reward the dog when you find them chewing appropriate items", "use bitter apple spray on furniture as a deterrent"], "donts": ["punish the dog after returning home to find destruction", "give the dog old shoes or clothing as toys — they cannot distinguish these from new items", "leave the dog with unsupervised access to dangerous chewables (cables, toxic plants)", "remove all toys — dogs need appropriate outlets", "underestimate the need for exercise and mental stimulation"]}',
 ARRAY['Returning home and punishing destruction that happened hours ago', 'Giving old shoes/socks as toys and wondering why the dog chews new ones', 'Underestimating exercise needs'],
 '{"links": [{"title": "ASPCA Destructive Chewing", "url": "https://www.aspca.org/pet-care/dog-care/common-dog-behavior-issues/destructive-chewing"}], "books": ["The Power of Positive Dog Training by Pat Miller"]}',
 true),

('jumping-on-people', 'Jumping on People', ARRAY['puppy', 'adult'],
 'Jumping up is a natural greeting behaviour for dogs but can be problematic — knocking over elderly people, children, or guests. Very common in enthusiastic breeds like Labradors, Boxers, and Goldens.',
 ARRAY['natural greeting behaviour learned as puppies when people found it cute', 'historically rewarded with attention (even negative attention is reinforcement)', 'high excitement state during greetings', 'insufficient training of an alternative greeting behaviour'],
 'The solution is teaching an incompatible behaviour — four paws on the floor (or a sit) is incompatible with jumping. Simultaneously, ensure jumping is never rewarded with any attention. Consistency across all family members and guests is essential.',
 ARRAY['"Four-on-the-floor" rule: Every person in the family rewards the dog ONLY when all four paws are on the ground. The moment the dog jumps, turn away completely and cross arms.', '"Sit to greet": Teach a reliable sit and ask for it before every greeting. Reward heavily for the sit.', '"Threshold practice": Practice calm greetings at the door daily, starting with the dog on a leash for management.'],
 '{"dos": ["be consistent — every family member and guest must follow the same rules", "reward four-on-the-floor immediately and enthusiastically", "ask guests to turn away when the dog jumps", "practice calm greetings regularly in low-arousal states", "manage with a leash at the door while training"], "donts": ["knee the dog in the chest — this causes injury and confusion", "grab the dog''s paws — this reinforces the jumping with physical interaction", "allow it sometimes and correct it other times — this makes it worse", "let guests decide whether to allow jumping — the rule must be universal", "yell at the dog — excited dogs interpret loud voices as excited participation"]}',
 ARRAY['Kneeing the dog (causes confusion and injury)', 'Allowing some people to accept jumping and others to correct it', 'Giving any attention at all when the dog jumps — even pushing away'],
 '{"links": [{"title": "Zak George Jumping Up", "url": "https://www.youtube.com/c/ZakGeorge"}], "books": ["How to Behave So Your Dog Behaves by Sophia Yin"]}',
 true),

('resource-guarding', 'Resource Guarding', ARRAY['puppy', 'adult'],
 'Resource guarding is when a dog growls, snaps, or bites to protect food, toys, sleeping spots, or people from perceived threats. It is normal canine behaviour that can escalate to dangerous levels if mishandled.',
 ARRAY['natural survival instinct — evolved to protect valuable resources', 'previous food insecurity (common in rescued street dogs)', 'punishment-based training that makes the dog feel more threatened', 'early warning signs ignored until behaviour escalated', 'genetic predisposition in some breeds'],
 'Resource guarding must be addressed with systematic counterconditioning — teaching the dog that an approach near their resource predicts something even better, rather than a threat. NEVER punish guarding — this triggers bites and damages trust.',
 ARRAY['"Trade up" game: Approach and offer something of higher value (chicken) in exchange for the guarded item. Dog learns approach = getting something better.', '"Food bowl exercises": While the dog eats from their bowl, approach and drop a high-value treat into the bowl. Dog learns your approach to the bowl predicts good things.', '"Drop it and leave it" commands: Trained with positive methods, these give the dog a way to release items without conflict.'],
 '{"dos": ["manage the environment to prevent rehearsal of guarding (feed in separate room)", "work with a certified behaviourist for severe cases (history of biting)", "teach drop it and leave it with positive reinforcement", "teach all family members to recognise early warning signs (stiffening, eating faster)", "respect the dog''s signals — never push past a growl without professional guidance"], "donts": ["punish or correct growling", "take food or items away forcefully and return them — this confirms the dog''s fear", "stare at or loom over the dog while they eat", "allow children near a dog that resource guards", "assume the dog is being dominant — resource guarding is fear-based"]}',
 ARRAY['Punishing growling (removes warning before bite, damages trust)', 'Forcefully removing items and holding them up "to show dominance"', 'Allowing children to take items from a guarding dog'],
 '{"links": [{"title": "Jean Donaldson on Resource Guarding", "url": "https://sfspca.org"}], "books": ["Mine! A Practical Guide to Resource Guarding in Dogs by Jean Donaldson"]}',
 true),

('fear-and-phobias', 'Fear and Phobias (Fireworks, Storms, Vehicles)', ARRAY['puppy', 'adult', 'senior'],
 'Fear responses to loud noises (Diwali crackers, thunderstorms, vehicles) are extremely common in Indian dogs. Repeated exposure to extreme fireworks in India can cause lasting noise phobias. This is a welfare issue requiring active management.',
 ARRAY['inadequate socialisation to sounds during the critical period (8–16 weeks)', 'single traumatic noise event', 'genetic predisposition to anxiety', 'owner''s anxious response inadvertently validating the fear', 'progressive sensitisation over years of unmanaged exposure'],
 'Desensitisation and counterconditioning to recorded sounds is the long-term solution. During acute fear events (Diwali), environmental management and medication (vet-prescribed) protect the dog from trauma. Do not expose an already-phobic dog to the feared stimulus without systematic protocols.',
 ARRAY['"Sound desensitisation": Play recordings of feared sounds at very low volume while the dog is relaxed and eating. Very gradually increase volume over weeks to months.', '"Safe space creation": Provide a quiet, dark den (under a bed, inside a wardrobe with door open) stocked with comfortable bedding. The dog chooses when to use it.', '"Thundershirt / anxiety wrap": Can reduce anxiety for mild to moderate cases. Fit correctly and introduce before a fear event.', '"Medication": Anti-anxiety medication (prescribed by a vet) is NOT a cop-out — it is humane management for severe phobias that prevents trauma.'],
 '{"dos": ["create and maintain a safe space year-round", "remain calm during the dog''s fear response — be matter-of-fact and reassuring", "consider vet-prescribed medication for Diwali season", "start sound desensitisation months before Diwali or monsoon season", "use pheromone diffusers (Adaptil) in the safe space"], "donts": ["force the dog outside during fireworks", "punish fear responses — this worsens anxiety", "over-soothe to the point of reinforcing panic (remain calm, not dismissive)", "ignore the problem until the fear is severe", "assume the dog will just get used to it without structured support"]}',
 ARRAY['Forcing the dog outside during fireworks to "show them nothing is wrong"', 'Punishing fear responses (hiding, trembling, urinating)', 'Waiting until Diwali to begin sound desensitisation (too late)'],
 '{"links": [{"title": "Dogs Trust Fireworks Guide", "url": "https://www.dogstrust.org.uk/help-advice/dog-behaviour-health/dealing-with-fireworks"}, {"title": "Sounds Scary Program", "url": "https://soundtherapy4pets.com"}], "books": ["Fired Up, Frantic, and Freaked Out by Laura VanArendonk Baugh"]}',
 true),

('basic-obedience-commands', 'Teaching Basic Commands (Sit, Stay, Come, Down)', ARRAY['puppy', 'adult'],
 'Basic obedience commands are the foundation of communication between owner and dog. A dog that knows sit, stay, come, and down reliably is safer, easier to manage, and more confident. These are life skills, not tricks.',
 ARRAY['owner has not invested time in training', 'inconsistent signals from different family members', 'training sessions too long and aversive', 'rewards not motivating enough for the individual dog', 'distractions too high before the command is reliably trained in low-distraction environments'],
 'All basic commands should be taught with positive reinforcement — the dog learns that offering the behaviour results in something they want (treats, toys, praise). Start in a quiet environment, gradually add distractions as the dog succeeds.',
 ARRAY['"Sit": Hold a treat above the dog''s nose and slowly move it back over the head. As the dog''s bottom lowers, say "Sit" and reward the moment they are seated.', '"Down": From a sit, hold a treat to the dog''s nose and lower it slowly to the floor between the front paws. As elbows touch the floor, say "Down" and reward.', '"Stay": Ask for a sit or down, take one step back, return and reward. Build distance and duration very gradually — one step or one second at a time.', '"Come (Recall)": Never chase the dog. Crouch down, open arms, use a happy voice: "Come!" Reward massively when they arrive. Never call the dog to punish.'],
 '{"dos": ["keep training sessions to 3–5 minutes, 2–3 times daily", "always end on success — finish with something the dog knows well", "use the highest-value treats for new or difficult behaviours", "train in quiet environments first, add distractions gradually", "be consistent — same word, same hand signal, every time"], "donts": ["repeat commands multiple times before the dog responds — this teaches them to ignore the first command", "train when the dog is tired, hungry, or overstimulated", "punish the dog for not responding to commands they haven''t mastered yet", "use the dog''s name as a command — names get attention, then give the command", "train for too long — short sessions are more effective than marathon sessions"]}',
 ARRAY['Repeating the command multiple times before the dog responds (teaches selective hearing)', 'Calling the dog to punish them (destroys recall reliability)', 'Training in too much distraction before the command is solid in quiet environments'],
 '{"links": [{"title": "Kikopup Training Videos", "url": "https://www.youtube.com/user/kikopup"}, {"title": "Zak George Beginner Training", "url": "https://www.youtube.com/c/ZakGeorge"}], "books": ["Don''t Shoot the Dog by Karen Pryor", "The Power of Positive Dog Training by Pat Miller"]}',
 true);
